emcc ./linter/cypher-lint.c \
./lib/annotation.c \
./lib/ast.c \
./lib/ast_all.c \
./lib/ast_all_nodes_scan.c \
./lib/ast_all_rels_scan.c \
./lib/ast_any.c \
./lib/ast_apply_operator.c \
./lib/ast_apply_all_operator.c \
./lib/ast_boolean.c \
./lib/ast_binary_operator.c \
./lib/ast_block_comment.c \
./lib/ast_call.c \
./lib/ast_case.c \
./lib/ast_collection.c \
./lib/ast_command.c \
./lib/ast_comment.c \
./lib/ast_comparison.c \
./lib/ast_create.c \
./lib/ast_create_node_props_index.c \
./lib/ast_create_node_prop_constraint.c \
./lib/ast_create_rel_prop_constraint.c \
./lib/ast_cypher_option.c \
./lib/ast_cypher_option_param.c \
./lib/ast_delete.c \
./lib/ast_drop_node_props_index.c \
./lib/ast_drop_node_prop_constraint.c \
./lib/ast_drop_rel_prop_constraint.c \
./lib/ast_error.c \
./lib/ast_explain_option.c \
./lib/ast_expression.c \
./lib/ast_extract.c \
./lib/ast_false.c \
./lib/ast_filter.c \
./lib/ast_float.c \
./lib/ast_foreach.c \
./lib/ast_function_name.c \
./lib/ast_identifier.c \
./lib/ast_index_name.c \
./lib/ast_integer.c \
./lib/ast_label.c \
./lib/ast_labels_operator.c \
./lib/ast_line_comment.c \
./lib/ast_list_comprehension.c \
./lib/ast_load_csv.c \
./lib/ast_match.c \
./lib/ast_match_hint.c \
./lib/ast_map.c \
./lib/ast_merge.c \
./lib/ast_merge_action.c \
./lib/ast_merge_properties.c \
./lib/ast_named_path.c \
./lib/ast_node_id_lookup.c \
./lib/ast_node_index_lookup.c \
./lib/ast_node_index_query.c \
./lib/ast_node_pattern.c \
./lib/ast_none.c \
./lib/ast_null.c \
./lib/ast_on_create.c \
./lib/ast_on_match.c \
./lib/ast_order_by.c \
./lib/ast_parameter.c \
./lib/ast_pattern.c \
./lib/ast_pattern_comprehension.c \
./lib/ast_pattern_path.c \
./lib/ast_proc_name.c \
./lib/ast_profile_option.c \
./lib/ast_projection.c \
./lib/ast_prop_name.c \
./lib/ast_property_operator.c \
./lib/ast_query.c \
./lib/ast_query_clause.c \
./lib/ast_query_option.c \
./lib/ast_range.c \
./lib/ast_reduce.c \
./lib/ast_rel_id_lookup.c \
./lib/ast_rel_index_lookup.c \
./lib/ast_rel_index_query.c \
./lib/ast_remove.c \
./lib/ast_remove_item.c \
./lib/ast_remove_labels.c \
./lib/ast_remove_property.c \
./lib/ast_rel_pattern.c \
./lib/ast_reltype.c \
./lib/ast_return.c \
./lib/ast_schema_command.c \
./lib/ast_set.c \
./lib/ast_set_all_properties.c \
./lib/ast_set_item.c \
./lib/ast_set_labels.c \
./lib/ast_set_property.c \
./lib/ast_shortest_path.c \
./lib/ast_single.c \
./lib/ast_slice_operator.c \
./lib/ast_sort_item.c \
./lib/ast_start.c \
./lib/ast_start_point.c \
./lib/ast_statement.c \
./lib/ast_statement_option.c \
./lib/ast_string.c \
./lib/ast_subscript_operator.c \
./lib/ast_map_projection.c \
./lib/ast_map_projection_selector.c \
./lib/ast_map_projection_literal.c \
./lib/ast_map_projection_property.c \
./lib/ast_map_projection_identifier.c \
./lib/ast_map_projection_all_properties.c \
./lib/ast_true.c \
./lib/ast_unary_operator.c \
./lib/ast_union.c \
./lib/ast_unwind.c \
./lib/ast_using_index.c \
./lib/ast_using_join.c \
./lib/ast_using_periodic_commit.c \
./lib/ast_using_scan.c \
./lib/ast_with.c \
./lib/errors.c \
./lib/operators.c \
./lib/parser.c \
./lib/parser_config.c \
./lib/quick_parser.c \
./lib/result.c \
./lib/segment.c \
./lib/string_buffer.c \
./lib/util.c \
./lib/vector.c